In [39]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler


import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [40]:
caminho='/content/german_credit_data.csv'

df=pd.read_csv(caminho)

In [41]:
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad

In [42]:
df['Risk']=np.where(df['Risk']=='bad',1,0)
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,0
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,1
2,2,49,male,1,own,little,NaN,2096,12,education,0
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,0
4,4,53,male,2,free,little,little,4870,24,car,1

In [43]:
novo_df=df[['Age','Credit amount','Duration','Risk']].copy()
novo_df

     Age  Credit amount  Duration  Risk
0     67           1169         6     0
1     22           5951        48     1
2     49           2096        12     0
3     45           7882        42     0
4     53           4870        24     1
..   ...            ...       ...   ...
995   31           1736        12     0
996   40           3857        30     0
997   38            804        12     0
998   23           1845        45     1
999   27           4576        45     0

[1000 rows x 4 columns]

In [44]:
fetures=novo_df.drop('Risk',axis=1)
labels=df['Risk']

In [45]:
X_train,X_test,y_train,y_test=train_test_split(fetures,labels,test_size=0.3,random_state=0)

In [50]:
pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    ('clf', DecisionTreeClassifier(random_state=42,max_depth=4))
])
pipe

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler()),
                ('clf', DecisionTreeClassifier(max_depth=4, random_state=42))])

In [51]:
pipe.fit(X_train,y_train)
y_predict=pipe.predict(X_test)

In [52]:
# 14. Métricas de Avaliação
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [53]:
acc = accuracy_score(y_test, y_predict)

print("Acurácia na validação:", round(acc, 4))
print("\nRelatório de classificação:")
print(classification_report(y_test,y_predict ))

Acurácia na validação: 0.72

Relatório de classificação:
              precision    recall  f1-score   support

           0       0.74      0.94      0.83       214
           1       0.54      0.16      0.25        86

    accuracy                           0.72       300
   macro avg       0.64      0.55      0.54       300
weighted avg       0.68      0.72      0.66       300