In [20]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

df = pd.DataFrame({
    "idade":   [25, 32, np.nan, 41],
    "salario": [3000, np.nan, 5000, 8000],
    "cidade":  ["SP", "RJ", np.nan, "SP"],
    "cargo":   ["analista", "gerente", "analista", np.nan]
})

In [21]:
df.head()

   idade  salario cidade     cargo
0   25.0   3000.0     SP  analista
1   32.0      NaN     RJ   gerente
2    NaN   5000.0    NaN  analista
3   41.0   8000.0     SP       NaN

In [22]:
colunas_numericas=df.select_dtypes(include='number').columns.tolist()
colunas_categoricas=df.select_dtypes(include='object').columns.tolist()

In [23]:
print(colunas_numericas)
print(colunas_categoricas)

['idade', 'salario']
['cidade', 'cargo']

In [24]:
pipeline_numerica=Pipeline([('imputer',SimpleImputer(strategy='median')),('scaler',StandardScaler())])

In [25]:
pipeline_categorica = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

In [26]:
preprocessador = ColumnTransformer([
    ("num", pipeline_numerica, colunas_numericas),
    ("cat", pipeline_categorica, colunas_categoricas)
])

In [27]:
dados_transformados = preprocessador.fit_transform(df)

In [28]:
df_final = pd.DataFrame(
    dados_transformados,
    columns=preprocessador.get_feature_names_out(),
    index=df.index
)

In [29]:
df_final.round(2).head()

,num__idade,num__salario,cat__cidade_RJ,cat__cidade_SP,cat__cargo_analista,cat__cargo_gerente
0,-1.32,-1.26,0.0,1.0,1.0,0.0
1,-0.09,-0.14,1.0,0.0,0.0,1.0
2,-0.09,-0.14,0.0,1.0,1.0,0.0
3,1.50,1.54,0.0,1.0,1.0,0.0