In [4]:
import os # para executar comandos de diretório
from google.colab import drive # habilitar google drive no colab
drive.mount('/content/drive')


from sklearn.feature_extraction.text import CountVectorizer

import pandas as pd

Mounted at /content/drive

In [5]:


df_csv=pd.read_csv('/content/drive/MyDrive/programacao/IA/WRKits/dados/corpus.csv')

df_csv

  Thor eating pizza, Loki is eating pizza, Ironman ate pizza already.
0           Apple is announcing new iphone tomorrow.
1          Tesla is announcing new model-3 tomorrow.
2         Google is announcing new pixel-6 tomorrow.
3      Microsoft is announcing new surface tomorrow.
4         Amazon is announcing new eco-dot tomorrow.
5     I am eating biryani and you are eating grapes.
6              I'm looking forward out next meeting.

In [6]:
corpus=pd.DataFrame(columns=['Text'])

corpus['Text']=df_csv.iloc[:,0]

corpus

                                              Text
0         Apple is announcing new iphone tomorrow.
1        Tesla is announcing new model-3 tomorrow.
2       Google is announcing new pixel-6 tomorrow.
3    Microsoft is announcing new surface tomorrow.
4       Amazon is announcing new eco-dot tomorrow.
5   I am eating biryani and you are eating grapes.
6            I'm looking forward out next meeting.

In [9]:
# 1. Cria a ferramenta que vai transformar o texto em uma "sacola de palavras" (Bag of Words).
# Por padrão, ele quebra o texto em palavras individuais, remove pontuações e deixa tudo em minúsculo.
vectorizer = CountVectorizer()

# 2. Faz duas coisas ao mesmo tempo:
# 'fit': Analisa a coluna 'Text' do seu banco de dados (corpus) para aprender todas as palavras únicas que existem ali.
# 'transform': Transforma cada texto em uma lista de números, contando quantas vezes cada palavra aprendida aparece.
# O resultado 'X' é salvo como uma matriz esparsa (formato otimizado que economiza memória).
X = vectorizer.fit_transform(corpus['Text'])

# 3. Extrai a lista com os nomes de todas as palavras únicas que o modelo aprendeu no passo anterior.
# Essa lista (tokens) vai estar exatamente na mesma ordem das colunas da matriz 'X'.
tokens = vectorizer.get_feature_names_out()

In [8]:
tokens

array(['am', 'amazon', 'and', 'announcing', 'apple', 'are', 'biryani',
       'dot', 'eating', 'eco', 'forward', 'google', 'grapes', 'iphone',
       'is', 'looking', 'meeting', 'microsoft', 'model', 'new', 'next',
       'out', 'pixel', 'surface', 'tesla', 'tomorrow', 'you'],
      dtype=object)