In [34]:
!pip install -q mlxtend


import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

In [35]:
df=pd.read_csv("/content/groceries - groceries.csv")
df.replace(np.nan,0,inplace=True)
df.head()

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3,tropical fruit,yogurt,coffee,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,whole milk,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,pip fruit,yogurt,cream cheese,meat spreads,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,other vegetables,whole milk,condensed milk,long life bakery product,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
df=df.drop(columns=['Item(s)'])
df.head()

,Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,Item 10,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,citrus fruit,semi-finished bread,margarine,ready soups,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,tropical fruit,yogurt,coffee,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,whole milk,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,pip fruit,yogurt,cream cheese,meat spreads,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,other vegetables,whole milk,condensed milk,long life bakery product,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [39]:
def removeZerosLista(l):
  return [item for item in l if item!=0]

In [40]:
listaDeTransacoes = []

for indice, linha in df.iterrows():
    itens = linha.values.tolist()
    listaDeTransacoes.append(removeZerosLista(itens))

In [30]:
from mlxtend.frequent_patterns import apriori, fpgrowth, association_rules

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [38]:
te=TransactionEncoder()

te_ary=te.fit(listaDeTransacoes).transform(listaDeTransacoes)

te_ary

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [41]:
te.columns_

['Instant food products',
 'UHT-milk',
 'abrasive cleaner',
 'artif. sweetener',
 'baby cosmetics',
 'baby food',
 'bags',
 'baking powder',
 'bathroom cleaner',
 'beef',
 'berries',
 'beverages',
 'bottled beer',
 'bottled water',
 'brandy',
 'brown bread',
 'butter',
 'butter milk',
 'cake bar',
 'candles',
 'candy',
 'canned beer',
 'canned fish',
 'canned fruit',
 'canned vegetables',
 'cat food',
 'cereals',
 'chewing gum',
 'chicken',
 'chocolate',
 'chocolate marshmallow',
 'citrus fruit',
 'cleaner',
 'cling film/bags',
 'cocoa drinks',
 'coffee',
 'condensed milk',
 'cooking chocolate',
 'cookware',
 'cream',
 'cream cheese',
 'curd',
 'curd cheese',
 'decalcifier',
 'dental care',
 'dessert',
 'detergent',
 'dish cleaner',
 'dishes',
 'dog food',
 'domestic eggs',
 'female sanitary products',
 'finished products',
 'fish',
 'flour',
 'flower (seeds)',
 'flower soil/fertilizer',
 'frankfurter',
 'frozen chicken',
 'frozen dessert',
 'frozen fish',
 'frozen fruits',
 'frozen meals',
 'frozen potato products',
 'frozen vegetables',
 'fruit/vegetable juice',
 'grapes',
 'hair spray',
 'ham',
 'hamburger meat',
 'hard cheese',
 'herbs',
 'honey',
 'house keeping products',
 'hygiene articles',
 'ice cream',
 'instant coffee',
 'jam',
 'ketchup',
 'kitchen towels',
 'kitchen utensil',
 'light bulbs',
 'liqueur',
 'liquor',
 'liquor (appetizer)',
 'liver loaf',
 'long life bakery product',
 'make up remover',
 'male cosmetics',
 'margarine',
 'mayonnaise',
 'meat',
 'meat spreads',
 'misc. beverages',
 'mustard',
 'napkins',
 'newspapers',
 'nut snack',
 'nuts/prunes',
 'oil',
 'onions',
 'organic products',
 'organic sausage',
 'other vegetables',
 'packaged fruit/vegetables',
 'pasta',
 'pastry',
 'pet care',
 'photo/film',
 'pickled vegetables',
 'pip fruit',
 'popcorn',
 'pork',
 'potato products',
 'potted plants',
 'preservation products',
 'processed cheese',
 'prosecco',
 'pudding powder',
 'ready soups',
 'red/blush wine',
 'rice',
 'roll products',
 'rolls/buns',
 'root vegetables',
 'rubbing alcohol',
 'rum',
 'salad dressing',
 'salt',
 'salty snack',
 'sauces',
 'sausage',
 'seasonal products',
 'semi-finished bread',
 'shopping bags',
 'skin care',
 'sliced cheese',
 'snack products',
 'soap',
 'soda',
 'soft cheese',
 'softener',
 'sound storage medium',
 'soups',
 'sparkling wine',
 'specialty bar',
 'specialty cheese',
 'specialty chocolate',
 'specialty fat',
 'specialty vegetables',
 'spices',
 'spread cheese',
 'sugar',
 'sweet spreads',
 'syrup',
 'tea',
 'tidbits',
 'toilet cleaner',
 'tropical fruit',
 'turkey',
 'vinegar',
 'waffles',
 'whipped/sour cream',
 'whisky',
 'white bread',
 'white wine',
 'whole milk',
 'yogurt',
 'zwieback']

In [43]:
df=pd.DataFrame(te_ary,columns=te.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [47]:
from mlxtend.frequent_patterns import apriori, association_rules

frequent_itemsets=apriori(df,min_support=0.01,use_colnames=True)

frequent_itemsets.sort_values(by=['support'],ascending=False)

      support                          itemsets
86   0.255516                      (whole milk)
55   0.193493                (other vegetables)
66   0.183935                      (rolls/buns)
75   0.174377                            (soda)
87   0.139502                          (yogurt)
..        ...                               ...
160  0.010066                (curd, rolls/buns)
236  0.010066       (waffles, other vegetables)
212  0.010066         (napkins, tropical fruit)
199  0.010066         (whole milk, hard cheese)
190  0.010066  (sausage, fruit/vegetable juice)

[333 rows x 2 columns]

In [52]:
from mlxtend.frequent_patterns import apriori, association_rules

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.4)
rules.sort_values(by=['lift'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
28,"(citrus fruit, root vegetables)",(other vegetables),0.017692,0.193493,0.010371,0.586207,3.029608,1.0,0.006948,1.949059,0.681990,0.051646,0.486932,0.319903
43,"(root vegetables, tropical fruit)",(other vegetables),0.021047,0.193493,0.012303,0.584541,3.020999,1.0,0.008231,1.941244,0.683367,0.060835,0.484867,0.324062
41,"(root vegetables, rolls/buns)",(other vegetables),0.024301,0.193493,0.012201,0.502092,2.594890,1.0,0.007499,1.619792,0.629935,0.059347,0.382637,0.282575
46,"(yogurt, root vegetables)",(other vegetables),0.025826,0.193493,0.012913,0.500000,2.584078,1.0,0.007916,1.613015,0.629266,0.062562,0.380043,0.283368
53,"(yogurt, whipped/sour cream)",(other vegetables),0.020742,0.193493,0.010168,0.490196,2.533410,1.0,0.006154,1.581995,0.618096,0.049826,0.367887,0.271372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23,(white bread),(whole milk),0.042095,0.255516,0.017082,0.405797,1.588147,1.0,0.006326,1.252912,0.386610,0.060892,0.201859,0.236325
0,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,1.0,0.007845,1.251315,0.389597,0.074113,0.200841,0.244103
21,(tropical fruit),(whole milk),0.104931,0.255516,0.042298,0.403101,1.577595,1.0,0.015486,1.247252,0.409045,0.132950,0.198238,0.284320
14,(oil),(whole milk),0.028063,0.255516,0.011286,0.402174,1.573968,1.0,0.004116,1.245319,0.375192,0.041449,0.196993,0.223172
24,(yogurt),(whole milk),0.139502,0.255516,0.056024,0.401603,1.571735,1.0,0.020379,1.244132,0.422732,0.165267,0.196226,0.310432