In [ ]:
import pandas as pd

In [ ]:
textos = [
    "A inteligência artificial está presente na indústria.",
    "A indústria utiliza dados e inteligência artificial.",
    "Modelos de linguagem ajudam na análise de textos."
]

In [ ]:
df=pd.DataFrame(columns=['Texto'])

df['Texto']=textos

df

                                               Texto
0  A inteligência artificial está presente na ind...
1  A indústria utiliza dados e inteligência artif...
2  Modelos de linguagem ajudam na análise de textos.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(df['Texto'])

print(vectorizer.get_feature_names_out())

print(X.toarray())

['ajudam' 'análise' 'artificial' 'dados' 'de' 'está' 'indústria'
 'inteligência' 'linguagem' 'modelos' 'na' 'presente' 'textos' 'utiliza']
[[0 0 1 0 0 1 1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1 0 0 0 0 0 1]
 [1 1 0 0 2 0 0 0 1 1 1 0 1 0]]

In [ ]:
contagem_palavras = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

contagem_palavras

,ajudam,análise,artificial,dados,de,está,indústria,inteligência,linguagem,modelos,na,presente,textos,utiliza
0,0,0,1,0,0,1,1,1,0,0,1,1,0,0
1,0,0,1,1,0,0,1,1,0,0,0,0,0,1
2,1,1,0,0,2,0,0,0,1,1,1,0,1,0